#!/bin/bash
echo "Script Description: This script is used to send emails as any email account directly to the inbox of the target person"
echo ~~Requirements :
echo "	1-Sendgrid activated account with a valid API Key (www.sendgrid.com)"
echo "~~Please enter the following details:"
read -p "	1-Sender email: " from
read -p "	2-Receiver email: " to
read -p "	3-Email subject: " subject
read -p "	4-Email header: " header
read -p "	5-Email message: " message
read -p "	6-Sendgrid API Key: " key
sendemail -s smtp.sendgrid.net:587 -xu apikey -xp "$key" -f "$from" -t "$to" -u "$subject" -m "$message" -o message-header="$header"

